[versions]
junit = "5.7.1"
kotlinx-coroutines = "1.5.0-native-mt"
kotlinx-serialization = "1.2.1"
ktor = "1.5.4"

[libraries]

# com.github.javaparser:javaparser-core - JavaParser
javaparser-core = { module = "com.github.javaparser:javaparser-core", version = "3.20.2" }

# com.gw2tb.api-generator:api-generator - api-generator
gw2api-generator = { module = "com.gw2tb.api-generator:api-generator", version = "0.3.0" }

# io.ktor - Ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# org.jetbrains.kotlinx:kotlinx-coroutines-[...] - kotlinx.coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

# org.jetbrains.kotlinx:kotlinx-serialization-[...] - kotlinx.serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.junit - JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# org.ow2.asm - ASM
asm = { module = "org.ow2.asm:asm", version = "9.1" }