[versions]
asm = "9.3"
api-generator = "0.6.0"
dokka = "1.7.10"
javaparser = "3.24.2"
junit = "5.8.2"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.3.3"
ktor = "2.0.3"


[libraries]
# com.github.javaparser:javaparser-core - JavaParser
javaparser-core = { module = "com.github.javaparser:javaparser-core", version.ref = "javaparser" }

# com.gw2tb.api-generator:api-generator - api-generator
gw2api-generator = { module = "com.gw2tb.api-generator:api-generator", version.ref = "api-generator" }

# io.ktor - Ktor
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

# org.jetbrains.kotlin - Kotlin
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

# org.jetbrains.kotlinx:kotlinx-coroutines-[...] - kotlinx.coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# org.jetbrains.kotlinx:kotlinx-serialization-[...] - kotlinx.serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# org.junit - JUnit
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# org.ow2.asm - ASM
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }


[plugins]
# org.jetbrains.dokka - dokka
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

# org.jetbrains.kotlin - Kotlin Gradle plugin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }