name: CI
on: push

jobs:
  jdk11:
    name: OpenJDK 11 (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: GW2ToolBelt/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
      - name: Gradle Build
        run: |
          ./gradlew --version --console=plain
          ./gradlew build -Psnapshot --info -S --console=plain